name: bmi_pj
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_animate: ^4.3.0
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
